ci: Move subiquity sha check to ci workflow

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -2,244 +2,254 @@ name: CI
 
 on:
   push:
-    branches:
-      - main
+  #   branches:
+  #     - main
 
-  pull_request:
-    branches:
-      - main
+  # pull_request:
+  #   branches:
+  #     - main
 
-  workflow_dispatch:
+#   workflow_dispatch:
 
-concurrency:
-  group: ${{ github.workflow }}-${{ github.ref }}
-  cancel-in-progress: true
+# concurrency:
+#   group: ${{ github.workflow }}-${{ github.ref }}
+#   cancel-in-progress: true
 
 jobs:
-  flutter-analyze:
+  # flutter-analyze:
+  #   runs-on: ubuntu-22.04
+  #   steps:
+  #     - uses: actions/checkout@v4
+  #       with:
+  #         submodules: recursive
+  #     - uses: asdf-vm/actions/install@v3
+  #     - uses: bluefireteam/melos-action@v2
+  #     - run: melos analyze
+
+  consistency-check:
     runs-on: ubuntu-22.04
     steps:
       - uses: actions/checkout@v4
         with:
           submodules: recursive
-      - uses: asdf-vm/actions/install@v3
-      - uses: bluefireteam/melos-action@v2
-      - run: melos analyze
-
-  bootstrap:
-    runs-on: ubuntu-22.04
-    strategy:
-      matrix:
-        target:
-          - ubuntu_bootstrap_test.dart
-          - screenshot_test.dart
-      fail-fast: false
-    steps:
-      - uses: actions/checkout@v4
-        with:
-          submodules: recursive
-      - uses: asdf-vm/actions/install@v3
-      - uses: bluefireteam/melos-action@v2
-      - run: |
-          sudo apt update
-          sudo apt install -y clang cmake curl libgtk-3-dev ninja-build pkg-config unzip
-          sudo apt install -y dbus-x11 network-manager upower
-          make install_deps
-      - run: |
-          sudo loginctl enable-linger $USER
-          sudo systemctl start user@$UID.service
-          echo "XDG_RUNTIME_DIR=/run/user/$UID" >> $GITHUB_ENV
-          # write any setting to force-start dconf.service (via xvfb because dbus-launch needs a display)
-          xvfb-run -a gsettings set org.gnome.desktop.interface color-scheme "'default'"
-      - run: xvfb-run -a -s '-screen 0 1024x768x24 +extension GLX' flutter test integration_test/${{matrix.target}}
-        working-directory: packages/ubuntu_bootstrap
-        env:
-          SUBIQUITY_REPLAY_TIMESCALE: 100
-
-  flutter-format:
-    runs-on: ubuntu-22.04
-    steps:
-      - uses: actions/checkout@v4
-        with:
-          submodules: recursive
-      - uses: asdf-vm/actions/install@v3
-      - uses: bluefireteam/melos-action@v2
-      - run: melos format
-
-  init-e2e:
-    runs-on: ubuntu-22.04
-    steps:
-      - uses: actions/checkout@v4
-        with:
-          submodules: recursive
-      - uses: asdf-vm/actions/install@v3
-      - uses: bluefireteam/melos-action@v2
-      - name: Install dependencies
+      - name: Check actual subiquity submodule sha matches expected
         run: |
-          sudo apt update
-          sudo apt install -y clang cmake curl libgtk-3-dev ninja-build pkg-config unzip
-          sudo apt install -y gnome-initial-setup network-manager
-      - name: Set up Go
-        uses: actions/setup-go@v5
-        with:
-          go-version-file: "./provd/go.mod"
-      - name: Build provd
-        run: go build ./cmd/provd
-        working-directory: provd
-      - name: Run provd
-        run: |
-          set -ux
-          set +e
-          mv provd/example.config.yaml provd/provd.yaml
-          sudo mkdir -p /run/provd
-          sudo chown $USER /run/provd
-          sudo provd/provd &
-          until [ -S /run/provd/provd.sock ]; do
-            sleep 1
-          done
-          sudo chmod go+rw /run/provd/provd.sock
+          ci/subiquity_integration
 
-      - run: xvfb-run -a -s '-screen 0 1024x768x24 +extension GLX' flutter test integration_test/e2e_test.dart
-        working-directory: packages/ubuntu_init
+  # bootstrap:
+  #   runs-on: ubuntu-22.04
+  #   strategy:
+  #     matrix:
+  #       target:
+  #         - ubuntu_bootstrap_test.dart
+  #         - screenshot_test.dart
+  #     fail-fast: false
+  #   steps:
+  #     - uses: actions/checkout@v4
+  #       with:
+  #         submodules: recursive
+  #     - uses: asdf-vm/actions/install@v3
+  #     - uses: bluefireteam/melos-action@v2
+  #     - run: |
+  #         sudo apt update
+  #         sudo apt install -y clang cmake curl libgtk-3-dev ninja-build pkg-config unzip
+  #         sudo apt install -y dbus-x11 network-manager upower
+  #         make install_deps
+  #     - run: |
+  #         sudo loginctl enable-linger $USER
+  #         sudo systemctl start user@$UID.service
+  #         echo "XDG_RUNTIME_DIR=/run/user/$UID" >> $GITHUB_ENV
+  #         # write any setting to force-start dconf.service (via xvfb because dbus-launch needs a display)
+  #         xvfb-run -a gsettings set org.gnome.desktop.interface color-scheme "'default'"
+  #     - run: xvfb-run -a -s '-screen 0 1024x768x24 +extension GLX' flutter test integration_test/${{matrix.target}}
+  #       working-directory: packages/ubuntu_bootstrap
+  #       env:
+  #         SUBIQUITY_REPLAY_TIMESCALE: 100
 
-  init:
-    runs-on: ubuntu-22.04
-    strategy:
-      matrix:
-        target:
-          - ubuntu_init_test.dart
-          - screenshot_test.dart
-      fail-fast: false
-    steps:
-      - uses: actions/checkout@v4
-        with:
-          submodules: recursive
-      - uses: asdf-vm/actions/install@v3
-      - uses: bluefireteam/melos-action@v2
-      - run: sudo apt update
-      - run: sudo apt install -y clang cmake curl libgtk-3-dev ninja-build pkg-config unzip
-      - run: xvfb-run -a -s '-screen 0 1024x768x24 +extension GLX' flutter test integration_test/${{matrix.target}}
-        working-directory: packages/ubuntu_init
+  # flutter-format:
+  #   runs-on: ubuntu-22.04
+  #   steps:
+  #     - uses: actions/checkout@v4
+  #       with:
+  #         submodules: recursive
+  #     - uses: asdf-vm/actions/install@v3
+  #     - uses: bluefireteam/melos-action@v2
+  #     - run: melos format
 
-  flutter-mocks:
-    runs-on: ubuntu-22.04
-    steps:
-      - uses: actions/checkout@v4
-        with:
-          submodules: recursive
-      - uses: asdf-vm/actions/install@v3
-      - uses: bluefireteam/melos-action@v2
-      - run: melos generate
-      - name: Check for outdated mocks
-        if: github.event_name == 'pull_request'
-        run: ./.github/scripts/check-outdated-files.sh
-      - name: Create PR
-        if: github.event_name == 'push'
-        uses: peter-evans/create-pull-request@v6
-        with:
-          add-paths: "**/*.mocks.dart"
-          title: "chore: regenerate mocks"
-          commit-message: "chore: regenerate mocks"
-          branch: create-pull-request/mocks
-          delete-branch: true
+  # init-e2e:
+  #   runs-on: ubuntu-22.04
+  #   steps:
+  #     - uses: actions/checkout@v4
+  #       with:
+  #         submodules: recursive
+  #     - uses: asdf-vm/actions/install@v3
+  #     - uses: bluefireteam/melos-action@v2
+  #     - name: Install dependencies
+  #       run: |
+  #         sudo apt update
+  #         sudo apt install -y clang cmake curl libgtk-3-dev ninja-build pkg-config unzip
+  #         sudo apt install -y gnome-initial-setup network-manager
+  #     - name: Set up Go
+  #       uses: actions/setup-go@v5
+  #       with:
+  #         go-version-file: "./provd/go.mod"
+  #     - name: Build provd
+  #       run: go build ./cmd/provd
+  #       working-directory: provd
+  #     - name: Run provd
+  #       run: |
+  #         set -ux
+  #         set +e
+  #         mv provd/example.config.yaml provd/provd.yaml
+  #         sudo mkdir -p /run/provd
+  #         sudo chown $USER /run/provd
+  #         sudo provd/provd &
+  #         until [ -S /run/provd/provd.sock ]; do
+  #           sleep 1
+  #         done
+  #         sudo chmod go+rw /run/provd/provd.sock
 
-  l10n:
-    runs-on: ubuntu-22.04
-    steps:
-      - uses: actions/checkout@v4
-        with:
-          submodules: recursive
-      - uses: asdf-vm/actions/install@v3
-      - uses: bluefireteam/melos-action@v2
-      - run: melos gen-l10n
-      - name: Check for outdated l10n
-        if: github.event_name == 'pull_request'
-        run: ./.github/scripts/check-outdated-files.sh
-      - name: Create PR
-        if: github.event_name == 'push'
-        uses: peter-evans/create-pull-request@v6
-        with:
-          add-paths: "**/l10n/*.dart"
-          title: "chore: regenerate l10n"
-          commit-message: "chore: regenerate l10n"
-          branch: create-pull-request/l10n
-          delete-branch: true
+  #     - run: xvfb-run -a -s '-screen 0 1024x768x24 +extension GLX' flutter test integration_test/e2e_test.dart
+  #       working-directory: packages/ubuntu_init
 
-  flutter-tests:
-    runs-on: ubuntu-22.04
-    steps:
-      - uses: actions/checkout@v4
-        with:
-          submodules: recursive
-      - uses: asdf-vm/actions/install@v3
-      - uses: bluefireteam/melos-action@v2
-      - name: Install dependencies
-        run: |
-          sudo apt update && sudo apt install lcov
-          make install_deps
-      - name: Setup environment
-        run: |
-          sudo loginctl enable-linger $USER
-          sudo systemctl start user@$UID.service
-          echo "XDG_RUNTIME_DIR=/run/user/$UID" >> $GITHUB_ENV
-      - run: melos coverage
-      - uses: codecov/codecov-action@v4
-        with:
-          flags: UI
-          token: ${{secrets.CODECOV_TOKEN}}
+  # init:
+  #   runs-on: ubuntu-22.04
+  #   strategy:
+  #     matrix:
+  #       target:
+  #         - ubuntu_init_test.dart
+  #         - screenshot_test.dart
+  #     fail-fast: false
+  #   steps:
+  #     - uses: actions/checkout@v4
+  #       with:
+  #         submodules: recursive
+  #     - uses: asdf-vm/actions/install@v3
+  #     - uses: bluefireteam/melos-action@v2
+  #     - run: sudo apt update
+  #     - run: sudo apt install -y clang cmake curl libgtk-3-dev ninja-build pkg-config unzip
+  #     - run: xvfb-run -a -s '-screen 0 1024x768x24 +extension GLX' flutter test integration_test/${{matrix.target}}
+  #       working-directory: packages/ubuntu_init
 
-  go-sanity:
-    name: "Go: Code sanity"
-    runs-on: ubuntu-latest
-    steps:
-      - name: Install dependencies
-        run: |
-          sudo apt-get update
-          sudo apt install -y libgtk-3-dev
-      - uses: actions/checkout@v4
-      - name: Go code sanity check
-        uses: canonical/desktop-engineering/gh-actions/go/code-sanity@main
-        with:
-          golangci-lint-configfile: ".golangci.yaml"
-          tools-directory: "./provd/tools"
-          working-directory: "./provd"
-      - name: Build cmd/provd
-        run: |
-          set -eu
-          cd provd
-          go build ./cmd/provd
+  # flutter-mocks:
+  #   runs-on: ubuntu-22.04
+  #   steps:
+  #     - uses: actions/checkout@v4
+  #       with:
+  #         submodules: recursive
+  #     - uses: asdf-vm/actions/install@v3
+  #     - uses: bluefireteam/melos-action@v2
+  #     - run: melos generate
+  #     - name: Check for outdated mocks
+  #       if: github.event_name == 'pull_request'
+  #       run: ./.github/scripts/check-outdated-files.sh
+  #     - name: Create PR
+  #       if: github.event_name == 'push'
+  #       uses: peter-evans/create-pull-request@v6
+  #       with:
+  #         add-paths: "**/*.mocks.dart"
+  #         title: "chore: regenerate mocks"
+  #         commit-message: "chore: regenerate mocks"
+  #         branch: create-pull-request/mocks
+  #         delete-branch: true
 
-  go-tests:
-    name: "Go: Tests"
-    runs-on: ubuntu-latest
-    steps:
-      - name: Install dependencies
-        run: |
-          sudo apt-get update
-          sudo apt install -y libgtk-3-dev
+  # l10n:
+  #   runs-on: ubuntu-22.04
+  #   steps:
+  #     - uses: actions/checkout@v4
+  #       with:
+  #         submodules: recursive
+  #     - uses: asdf-vm/actions/install@v3
+  #     - uses: bluefireteam/melos-action@v2
+  #     - run: melos gen-l10n
+  #     - name: Check for outdated l10n
+  #       if: github.event_name == 'pull_request'
+  #       run: ./.github/scripts/check-outdated-files.sh
+  #     - name: Create PR
+  #       if: github.event_name == 'push'
+  #       uses: peter-evans/create-pull-request@v6
+  #       with:
+  #         add-paths: "**/l10n/*.dart"
+  #         title: "chore: regenerate l10n"
+  #         commit-message: "chore: regenerate l10n"
+  #         branch: create-pull-request/l10n
+  #         delete-branch: true
 
-      - name: Checkout code
-        uses: actions/checkout@v4
+  # flutter-tests:
+  #   runs-on: ubuntu-22.04
+  #   steps:
+  #     - uses: actions/checkout@v4
+  #       with:
+  #         submodules: recursive
+  #     - uses: asdf-vm/actions/install@v3
+  #     - uses: bluefireteam/melos-action@v2
+  #     - name: Install dependencies
+  #       run: |
+  #         sudo apt update && sudo apt install lcov
+  #         make install_deps
+  #     - name: Setup environment
+  #       run: |
+  #         sudo loginctl enable-linger $USER
+  #         sudo systemctl start user@$UID.service
+  #         echo "XDG_RUNTIME_DIR=/run/user/$UID" >> $GITHUB_ENV
+  #     - run: melos coverage
+  #     - uses: codecov/codecov-action@v4
+  #       with:
+  #         flags: UI
+  #         token: ${{secrets.CODECOV_TOKEN}}
 
-      - name: Set up Go
-        uses: actions/setup-go@v5
-        with:
-          go-version-file: "./provd/go.mod"
+  # go-sanity:
+  #   name: "Go: Code sanity"
+  #   runs-on: ubuntu-latest
+  #   steps:
+  #     - name: Install dependencies
+  #       run: |
+  #         sudo apt-get update
+  #         sudo apt install -y libgtk-3-dev
+  #     - uses: actions/checkout@v4
+  #     - name: Go code sanity check
+  #       uses: canonical/desktop-engineering/gh-actions/go/code-sanity@main
+  #       with:
+  #         golangci-lint-configfile: ".golangci.yaml"
+  #         tools-directory: "./provd/tools"
+  #         working-directory: "./provd"
+  #     - name: Build cmd/provd
+  #       run: |
+  #         set -eu
+  #         cd provd
+  #         go build ./cmd/provd
 
-      - name: Run tests
-        run: |
-          set -eu
+  # go-tests:
+  #   name: "Go: Tests"
+  #   runs-on: ubuntu-latest
+  #   steps:
+  #     - name: Install dependencies
+  #       run: |
+  #         sudo apt-get update
+  #         sudo apt install -y libgtk-3-dev
 
-          cd provd
-          go test -coverpkg=./... -coverprofile=/tmp/coverage.out -covermode=set ./... -shuffle=on
-      - name: Run tests (with race detector)
-        run: |
+  #     - name: Checkout code
+  #       uses: actions/checkout@v4
 
-          cd provd
-          go test -race ./...
-      - name: Upload coverage to Codecov
-        uses: codecov/codecov-action@v4
-        with:
-          file: /tmp/coverage.out
-          flags: provd
-          token: ${{secrets.CODECOV_TOKEN}}
+  #     - name: Set up Go
+  #       uses: actions/setup-go@v5
+  #       with:
+  #         go-version-file: "./provd/go.mod"
+
+  #     - name: Run tests
+  #       run: |
+  #         set -eu
+
+  #         cd provd
+  #         go test -coverpkg=./... -coverprofile=/tmp/coverage.out -covermode=set ./... -shuffle=on
+  #     - name: Run tests (with race detector)
+  #       run: |
+
+  #         cd provd
+  #         go test -race ./...
+  #     - name: Upload coverage to Codecov
+  #       uses: codecov/codecov-action@v4
+  #       with:
+  #         file: /tmp/coverage.out
+  #         flags: provd
+  #         token: ${{secrets.CODECOV_TOKEN}}
